server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}
