server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://sso.com
#          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}
