server:
  port: 9000

logging:
  level:
    org.springframework.security.oauth2: trace
    org.springframework.security: trace
    root: info

spring:
  # DataSource Configuration for H2
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  # JPA Configuration
  jpa:
    # 或者针对MySQL模式使用 org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # 使用 schema.sql 和 data.sql, 因此关闭自动DDL
      ddl-auto: create
    # 显示SQL语句，生产环境关闭
    show-sql: true
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        # 安全起见，仅允许本地访问
        web-allow-others: false
  # Spring SQL Initialization
  sql:
    init:
      # 始终执行 schema.sql 和 data.sql
      mode: always
      schema-locations: ""
#      schema-locations: classpath:schema.sql
      # 设置为空字符串，不初始化数据
      data-locations: ""
#       初始化出错结束应用
      continue-on-error: false
