server:
  port: 9000

logging:
  level:
    org.springframework.security: debug

#spring:
#  datasource:
#    url: jdbc:mysql://1.12.46.222:3306/oauth-demo?useSSL=false
#    username: oauth-demo
#    password: F5tJs7jkA2JPLpW6
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${JWK_SET_URI:http://localhost:9000/.well-known/jwks.json}
#      authorizationserver:
#        client:
#          client:
#            registration:
#              client-id: "client"
#              client-secret: "{noop}secret"
#              client-authentication-methods:
#                - "client_secret_basic"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "http://localhost:8080/login/oauth2/code/client"
#              post-logout-redirect-uris:
#                - "http://localhost:8080/"
#              scopes:
#                - "openid"
#                - "profile"
#            require-authorization-consent: true