server:
  port: 8080

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      client:
        registration:
          client:
            client-id: client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
            client-name: Client App
        provider:
          client:
            issuer-uri: http://sso.com
            authorization-uri: http://sso.com/oauth2/authorize
            token-uri: http://sso.com/oauth2/token
            jwk-set-uri: http://sso.com/oauth2/jwks
            user-info-uri: http://sso.com/userinfo
            user-name-attribute: sub

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          web-client-auth-code:
#            provider: my-sso
#            client-id: web-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#        provider:
#          # 认证服务器配置
#          my-sso:
#            authorization-uri: http://localhost:8080/oauth/authorize
#            token-uri: http://localhost:8080/oauth/token
#            user-info-uri: http://localhost:8080/api/userinfo
#            user-name-attribute: name
