server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          web-client-auth-code:
            provider: my-sso
            client-id: web-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          # 认证服务器配置
          my-sso:
            authorization-uri: http://localhost:8080/oauth/authorize
            token-uri: http://localhost:8080/oauth/token
            user-info-uri: http://localhost:8080/api/userinfo
            user-name-attribute: name
